apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slurm-home
  namespace: slurm
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 50Gi
